### ISSUE TITLE
How to solve wavelength limitations？

### ISSUE THREAD

**Issue by Springder** [simonrp84/PyCoxMunk#8]
The maximum wavelength is 4.5 microns. What should I do if I need a larger wavelength?

**Comment by simon-sat** [comment]
Beyond 4.5 micron there is very little solar radiation, and hence the sea surface reflectance is very small. You could extend the `CM_DATA_DICT` in `CM_Constants.py` to include data for higher wavelengths but you would need to find and include this information yourself and because the solar contribution is so small I struggle to think it will be of much value, to be honest.

If you do proceed to include higher wavelengths, though, a pull request with your conclusions would be most welcome!
